<Project>
  <Target Name="VersionApplicationManifest" BeforeTargets="PrepareForBuild"
          Condition="'$(MSBuildProjectName)' == 'GuGuGaGaTranslator.App'">
    <MakeDir Directories="$(IntermediateOutputPath)" />
    <Copy SourceFiles="$(MSBuildProjectDirectory)/app.manifest"
          DestinationFiles="$(IntermediateOutputPath)Versioned.app.manifest" />
    <XmlPoke XmlInputPath="$(IntermediateOutputPath)Versioned.app.manifest"
             Query="/*[local-name()='assembly']/*[local-name()='assemblyIdentity']/@version"
             Value="$(Version).0" />
    <PropertyGroup>
      <ApplicationManifest>$(IntermediateOutputPath)Versioned.app.manifest</ApplicationManifest>
    </PropertyGroup>
  </Target>
</Project>
