<Project>
  <PropertyGroup>
    <Version>1.5.0</Version>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <InvariantGlobalization>false</InvariantGlobalization>
    <!-- Windows 10 2004 为最低支持版本。 -->
    <SupportedOSPlatformVersion>10.0.19041.0</SupportedOSPlatformVersion>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
  </PropertyGroup>
</Project>
